#!/bin/bash

# Quick Commands untuk Menambahkan MySQL ke Vercel
# Copy dan paste command ini satu per satu di terminal BARU

echo "=================================================="
echo "  MySQL Environment Variables Setup untuk Vercel"
echo "=================================================="
echo ""
echo "PENTING: Buka terminal BARU untuk menjalankan commands ini!"
echo "Atau tekan Ctrl+C pada vercel command yang masih running."
echo ""
echo "=================================================="
echo "  Opsi 1: Vercel Dashboard (PALING MUDAH)"
echo "=================================================="
echo ""
echo "Buka browser:"
echo "https://vercel.com/amdanibiks-projects/coffee/settings/environment-variables"
echo ""
echo "Tambahkan variables berikut:"
echo "  MYSQL_HOST          = your-mysql-host.com"
echo "  MYSQL_PORT          = 3306"
echo "  MYSQL_DATABASE      = coffee_db"
echo "  MYSQL_USER          = your-username"
echo "  MYSQL_PASSWORD      = your-password"
echo "  MYSQL_DATABASE_URL  = mysql://user:pass@host:3306/db"
echo ""
echo "=================================================="
echo "  Opsi 2: Vercel CLI Commands"
echo "=================================================="
echo ""
echo "Jalankan commands berikut di TERMINAL BARU:"
echo ""
echo "# 1. MYSQL_HOST"
echo 'vercel env add MYSQL_HOST'
echo ""
echo "# 2. MYSQL_PORT"
echo 'vercel env add MYSQL_PORT'
echo ""
echo "# 3. MYSQL_DATABASE"
echo 'vercel env add MYSQL_DATABASE'
echo ""
echo "# 4. MYSQL_USER"
echo 'vercel env add MYSQL_USER'
echo ""
echo "# 5. MYSQL_PASSWORD"
echo 'vercel env add MYSQL_PASSWORD'
echo ""
echo "# 6. MYSQL_DATABASE_URL"
echo 'vercel env add MYSQL_DATABASE_URL'
echo ""
echo "=================================================="
echo "  Opsi 3: Script Otomatis"
echo "=================================================="
echo ""
echo "./add-mysql-to-vercel.sh"
echo ""
echo "=================================================="
echo "  Setelah Selesai:"
echo "=================================================="
echo ""
echo "1. Verify environment variables:"
echo "   vercel env ls"
echo ""
echo "2. Deploy ulang:"
echo "   vercel --prod"
echo ""
echo "3. Test koneksi:"
echo "   ./test-mysql-connector.sh"
echo ""
