#!/bin/bash

# Quick reference guide for Coffee Database Connector

echo "================================================"
echo "Coffee Database Connector - Quick Reference"
echo "================================================"
echo ""

echo "📚 DOCUMENTATION FILES:"
echo "1. README.md                      - Main documentation"
echo "2. DATABASE_SCHEMA_FOR_AI.md      - Complete schema for AI (START HERE for schema info!)"
echo "3. SCHEMA_INTROSPECTION.md        - Schema introspection feature details"
echo "4. BIZCOPILOT_CONNECTION_FIXED.md - Connection setup guide"
echo "5. SETUP_BIZCOPILOT.md            - Quick setup for BizCopilot"
echo "6. FINAL_FIX_SUMMARY.md           - Summary of all fixes"
echo ""

echo "🔗 CONNECTOR ENDPOINTS:"
echo ""
echo "PUBLIC (No Auth):"
echo "  GET  /api/connector/metadata  - Connector information"
echo "  GET  /api/connector/health    - Health check"
echo ""
echo "PROTECTED (Requires X-API-Key):"
echo "  POST /execute                 - Main query execution (BizCopilot primary)"
echo "  GET  /introspect              - Get database schema structure"
echo "  GET  /schema                  - Get schema text for AI"
echo "  GET  /sample-data             - Get sample data from tables"
echo "  POST /api/test-connection     - Test database connection"
echo "  POST /api/query               - Execute custom query"
echo ""

echo "📊 DATABASE SCHEMA:"
echo ""
echo "Tables:"
echo "  1. tenants        - Coffee shop branches/locations"
echo "  2. orders         - Customer orders per tenant"
echo "  3. order_details  - Order line items with products"
echo ""
echo "Relationships:"
echo "  tenants (1) ─────< orders (many)"
echo "  orders (1) ─────< order_details (many)"
echo ""

echo "🧪 TESTING:"
echo ""
echo "Test Execute Endpoint:"
echo "  API_KEY=your-key ./test-execute-endpoint.sh"
echo ""
echo "Test Schema Introspection:"
echo "  API_KEY=your-key ./test-introspect.sh"
echo ""
echo "Manual Test:"
echo "  curl -X POST https://your-connector-url/execute \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H 'X-API-Key: your-key' \\"
echo "    -d '{\"query\": \"SELECT * FROM tenants LIMIT 5\"}'"
echo ""

echo "🚀 DEPLOYMENT:"
echo ""
echo "1. Commit changes:"
echo "   git add ."
echo "   git commit -m 'Update connector'"
echo "   git push origin main"
echo ""
echo "2. Vercel will auto-deploy"
echo ""
echo "3. Configure in BizCopilot:"
echo "   - URL: https://your-connector-url"
echo "   - API Key: [your CONNECTOR_API_KEY]"
echo "   - Database Type: PostgreSQL"
echo ""

echo "💡 COMMON QUERIES:"
echo ""
echo "Get all tenants:"
echo "  SELECT * FROM tenants;"
echo ""
echo "Daily sales by tenant:"
echo "  SELECT t.name, COUNT(o.id) as orders, SUM(o.total) as revenue"
echo "  FROM orders o JOIN tenants t ON o.tenant_id = t.id"
echo "  WHERE o.order_date = '2025-11-04'"
echo "  GROUP BY t.name;"
echo ""
echo "Best selling products:"
echo "  SELECT product_name, SUM(qty) as total_sold"
echo "  FROM order_details"
echo "  GROUP BY product_name"
echo "  ORDER BY total_sold DESC LIMIT 5;"
echo ""

echo "🔐 SECURITY:"
echo "- API Key required in X-API-Key header"
echo "- HMAC signature supported (optional)"
echo "- HTTPS enabled (via Vercel)"
echo ""

echo "📞 SUPPORT:"
echo "- Repository: amdanibik/coffe"
echo "- Deployment: Vercel"
echo "- Compatible with: BizCopilot.app"
echo ""

echo "================================================"
echo "For detailed schema documentation, see:"
echo "👉 DATABASE_SCHEMA_FOR_AI.md"
echo "================================================"
